[helpers]

[default]
depends = []

[default.files]
"home/.gitconfig" = "~/.gitconfig"
"home/.bashrc" = "~/.bashrc"
"home/.bash_profile" = "~/.bash_profile"
"nvim" = "~/.config/nvim"

[default.variables]

[settings]
default_target_type = "automatic"
